(()=>{
  const es=document.documentElement.lang==="es",ui=es?{
    open:"Abrir la Biblia",load:"Cargando los libros…",ready:"Biblia lista · 66 libros",fail:"No se pudo cargar la Biblia. Comprueba la conexión y vuelve a intentarlo.",chapter:"Capítulo",verse:"versículos",missing:"[Este número de versículo no tiene texto en esta edición.]",highlight:"Resaltar versículo",unhighlight:"Quitar resaltado",bookmark:"Guardar marcador",unbookmark:"Quitar marcador",marked:"Versículo resaltado.",unmarked:"Se quitó el resaltado.",savedMark:"Marcador guardado.",unsavedMark:"Se quitó el marcador.",emptyBookmarks:"Todavía no hay versículos guardados.",loadingBook:"Abriendo ",bookError:"No se pudo abrir el libro. Comprueba la conexión.",noteSaved:"Guardado en este dispositivo · ",shareCopied:"Enlace copiado para compartir.",backupName:"selah-notas-es.json",edition:"Reina-Valera 1909",restoreBad:"No se pudo leer la copia de Selah.",restored:"Copia restaurada en este dispositivo.",progress:"Guardados ",books:" libros…",downloaded:"Biblia guardada para leer sin conexión.",downloadError:"No se pudo completar la descarga. Comprueba la conexión.",offlineUnsupported:"La lectura sin conexión no está disponible en este navegador.",shareTitle:"Selah · "
  }:{
    open:"Abrir a Bíblia",load:"Carregando os livros…",ready:"Bíblia pronta · 66 livros",fail:"Não foi possível carregar a Bíblia. Verifique a conexão e tente novamente.",chapter:"Capítulo",verse:"versículos",missing:"[Esta posição de versículo não tem texto nesta edição.]",highlight:"Destacar versículo",unhighlight:"Remover destaque",bookmark:"Salvar marcador",unbookmark:"Remover marcador",marked:"Versículo destacado.",unmarked:"Destaque removido.",savedMark:"Marcador salvo.",unsavedMark:"Marcador removido.",emptyBookmarks:"Ainda não há versículos salvos.",loadingBook:"Abrindo ",bookError:"Não foi possível abrir o livro. Verifique a conexão.",noteSaved:"Salvo neste dispositivo · ",shareCopied:"Link copiado para compartilhar.",backupName:"selah-notas-pt-br.json",edition:"Bíblia Livre 2018",restoreBad:"Não foi possível ler a cópia do Selah.",restored:"Cópia restaurada neste dispositivo.",progress:"Salvos ",books:" livros…",downloaded:"Bíblia salva para leitura offline.",downloadError:"Não foi possível concluir o download. Verifique a conexão.",offlineUnsupported:"A leitura offline não está disponível neste navegador.",shareTitle:"Selah · "
  };
  const $=id=>document.getElementById(id),key="selah.reader."+document.documentElement.lang+".v1",base="./",cacheName="selah-bible-"+document.documentElement.lang;
  let bible,currentBook,bookIndex=39,chapterIndex=0,selected=0,store=(()=>{try{return JSON.parse(localStorage.getItem(key)||"{}")}catch{return{}}})();
  const persist=()=>localStorage.setItem(key,JSON.stringify(store)),chapterKey=()=>bible.books[bookIndex].id+":"+(chapterIndex+1),verseKey=n=>chapterKey()+":"+n,esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  async function fetchLocal(url){const cached="caches"in window?await caches.open(cacheName).then(c=>c.match(url)).catch(()=>null):null;return cached||fetch(url)}
  function renderBooks(){ $("book").innerHTML=bible.books.map((b,i)=>`<option value="${i}">${esc(b.name)}</option>`).join("");$("book").value=bookIndex;renderChapters() }
  function renderChapters(){const b=bible.books[bookIndex];$("chapter").innerHTML=Array.from({length:b.chapters},(_,i)=>`<option value="${i}">${ui.chapter} ${i+1}</option>`).join("");$("chapter").value=chapterIndex;renderChapter()}
  function renderChapter(){if(!currentBook)return;selected=0;const name=bible.books[bookIndex].name,verses=currentBook.chapters[chapterIndex];$("reader-title").textContent=name+" "+(chapterIndex+1);$("chapter-title").textContent=name+" "+(chapterIndex+1);$("verse-count").textContent=verses.length+" "+ui.verse;$("verses").innerHTML=verses.map((text,i)=>{const n=i+1,k=verseKey(n);return `<button type="button" class="verse${store.highlights?.includes(k)?" highlighted":""}" data-verse="${n}" aria-pressed="false"><sup>${n}</sup>${text?esc(text):`<i>${ui.missing}</i>`}</button>`}).join("");$("verses").querySelectorAll("[data-verse]").forEach(el=>el.onclick=()=>{selected=Number(el.dataset.verse);renderSelection()});$("reflection").value=store.notes?.[chapterKey()]||"";$("previous").disabled=bookIndex===0&&chapterIndex===0;$("next").disabled=bookIndex===bible.books.length-1&&chapterIndex===currentBook.chapters.length-1;$("highlight").disabled=$("bookmark").disabled=true;$("selection-status").textContent="";renderBookmarks()}
  function renderSelection(){const k=verseKey(selected),hasH=store.highlights?.includes(k),hasB=store.bookmarks?.includes(k);$("verses").querySelectorAll("[data-verse]").forEach(el=>{const on=Number(el.dataset.verse)===selected;el.classList.toggle("selected",on);el.setAttribute("aria-pressed",String(on))});$("highlight").disabled=$("bookmark").disabled=!selected;$("highlight").textContent=hasH?ui.unhighlight:ui.highlight;$("bookmark").textContent=hasB?ui.unbookmark:ui.bookmark;$("selection-status").textContent=bible.books[bookIndex].name+" "+(chapterIndex+1)+":"+selected}
  async function loadBook(index){const meta=bible.books[index];if(currentBook?.id===meta.id)return currentBook;$("load-status").textContent=ui.loadingBook+meta.name+"…";const r=await fetchLocal(base+"books/"+encodeURIComponent(meta.id)+".json");if(!r.ok)throw Error();const b=await r.json();if(b.id!==meta.id||b.chapters?.length!==meta.chapters||b.chapters.reduce((a,c)=>a+c.length,0)!==meta.verses)throw Error();return b}
  async function navigate(index,chapter){$("book").disabled=$("chapter").disabled=$("previous").disabled=$("next").disabled=true;try{currentBook=await loadBook(index);bookIndex=index;chapterIndex=chapter;$("book").value=index;renderChapters();history.replaceState(null,"",location.pathname+"?book="+bible.books[index].id+"&chapter="+(chapter+1));$("load-status").textContent=ui.ready}catch{$("load-status").textContent=ui.bookError}finally{$("book").disabled=$("chapter").disabled=false;$("previous").disabled=!currentBook||bookIndex===0&&chapterIndex===0;$("next").disabled=!currentBook||bookIndex===bible.books.length-1&&chapterIndex===currentBook.chapters.length-1}}
  async function move(delta){let b=bookIndex,c=chapterIndex+delta;if(c<0){b--;c=bible.books[b].chapters-1}else if(c>=bible.books[b].chapters){b++;c=0}await navigate(b,c)}
  function renderBookmarks(){const saved=store.bookmarks||[];$("bookmark-list").innerHTML=saved.length?saved.map(k=>{const [id,c,v]=k.split(":"),book=bible.books.find(b=>b.id===id);return `<li><button type="button" data-mark="${esc(k)}">${esc(book?.name||id)} ${c}:${v}</button></li>`}).join(""):`<li>${ui.emptyBookmarks}</li>`;$("bookmark-list").querySelectorAll("[data-mark]").forEach(el=>el.onclick=async()=>{const [id,c,v]=el.dataset.mark.split(":"),i=bible.books.findIndex(b=>b.id===id);await navigate(i,Number(c)-1);selected=Number(v);renderSelection();$("verses").querySelector(`[data-verse="${v}"]`)?.scrollIntoView({behavior:"smooth",block:"center"})})}
  async function start(){if(bible)return;$("reader").hidden=false;$("reader").scrollIntoView({behavior:"smooth",block:"start"});$("start").disabled=true;$("load-status").textContent=ui.load;try{const r=await fetchLocal(base+"manifest.json");if(!r.ok)throw Error();const d=await r.json();if(d.books?.length!==66||d.totalChapters!==1189||d.books.reduce((n,b)=>n+b.chapters,0)!==1189)throw Error();bible=d;const q=new URLSearchParams(location.search),i=d.books.findIndex(b=>b.id===q.get("book"));if(i>=0)bookIndex=i;const n=Number(q.get("chapter"));chapterIndex=Number.isInteger(n)&&n>0&&n<=d.books[bookIndex].chapters?n-1:0;currentBook=await loadBook(bookIndex);window.selahAnalytics?.reader();renderBooks();$("load-status").textContent=ui.ready;$("book").disabled=$("chapter").disabled=false}catch{$("load-status").textContent=ui.fail;$("start").disabled=false}}
  $("start").onclick=start;$("book").onchange=()=>navigate(Number($("book").value),0);$("chapter").onchange=()=>navigate(bookIndex,Number($("chapter").value));$("previous").onclick=()=>move(-1);$("next").onclick=()=>move(1);
  $("highlight").onclick=()=>{const k=verseKey(selected),set=new Set(store.highlights||[]),has=set.has(k);has?set.delete(k):set.add(k);store.highlights=[...set];persist();renderChapter();selected=Number(k.split(":").pop());renderSelection();$("selection-status").textContent=has?ui.unmarked:ui.marked};
  $("bookmark").onclick=()=>{const k=verseKey(selected),set=new Set(store.bookmarks||[]),has=set.has(k);has?set.delete(k):set.add(k);store.bookmarks=[...set];persist();renderChapter();selected=Number(k.split(":").pop());renderSelection();$("selection-status").textContent=has?ui.unsavedMark:ui.savedMark};
  $("reflection").oninput=()=>{store.notes={...(store.notes||{}),[chapterKey()]:$("reflection").value};persist();window.selahAnalytics?.reflection($("reflection").value);$("note-status").textContent=ui.noteSaved+new Date().toLocaleTimeString(document.documentElement.lang,{hour:"numeric",minute:"2-digit"})};
  $("backup").onclick=()=>{const a=document.createElement("a"),blob=new Blob([JSON.stringify({edition:ui.edition,exportedAt:new Date().toISOString(),notes:store.notes||{},bookmarks:store.bookmarks||[],highlights:store.highlights||{}},null,2)],{type:"application/json"});a.href=URL.createObjectURL(blob);a.download=ui.backupName;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
  $("restore").onclick=()=>$("restore-file").click();$("restore-file").onchange=async e=>{try{const f=e.target.files?.[0];if(!f||f.size>1048576)throw Error();const d=JSON.parse(await f.text());if(!String(d.edition||"").includes(ui.edition)||!d.notes||typeof d.notes!=="object"||Array.isArray(d.notes))throw Error();store.notes={...d.notes,...(store.notes||{})};for(const k of ["bookmarks","highlights"])store[k]=[...new Set([...(Array.isArray(d[k])?d[k]:[]),...(store[k]||[])].filter(x=>typeof x==="string"&&/^[A-Z0-9]{3}:\d+:\d+$/.test(x)))];persist();$("reflection").value=store.notes[chapterKey()]||"";renderChapter();$("note-status").textContent=ui.restored}catch{$("note-status").textContent=ui.restoreBad}finally{e.target.value=""}};
  $("share").onclick=async()=>{const b=bible.books[bookIndex],verse=currentBook.chapters[chapterIndex][selected-1],ref=b.name+" "+(chapterIndex+1)+(selected?":"+selected:"");try{if(navigator.share)await navigator.share({title:ui.shareTitle+ref,text:verse||ref,url:location.origin+location.pathname+"?book="+b.id+"&chapter="+(chapterIndex+1)});else{await navigator.clipboard.writeText(ref+"\n"+location.href);$("selection-status").textContent=ui.shareCopied}}catch{}};
  $("offline").onclick=async()=>{const button=$("offline"),status=$("offline-status");if(!("serviceWorker"in navigator)||!("caches"in window)){status.textContent=ui.offlineUnsupported;return}button.disabled=true;try{if(!bible)await start();if(!bible)throw Error();await navigator.serviceWorker.register("./sw.js");await navigator.serviceWorker.ready;const cache=await caches.open(cacheName),assets=["./","./reader.js","./manifest.json",...Array.from({length:66},(_,i)=>"./books/"+bible.books[i].id+".json")];for(let i=0;i<assets.length;i++){const url=new URL(assets[i],location.href).href,res=await fetch(url);if(!res.ok)throw Error();await cache.put(url,res);status.textContent=ui.progress+i+"/"+assets.length+ui.books}status.textContent=ui.downloaded}catch{status.textContent=ui.downloadError}finally{button.disabled=false}};
  if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});if(new URLSearchParams(location.search).has("book"))start();
})();
